"""add job offer required years

Revision ID: 1caa8ba11920
Revises: 514f8567d649
Create Date: 2026-09-03 14:16:38.302350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1caa8ba11920'
down_revision: Union[str, Sequence[str], None] = '514f8567d649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_offers', sa.Column('required_years', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_offers', 'required_years')
    # ### end Alembic commands ###
