"""create job_skill_matches

Revision ID: 2d67168d9cbd
Revises: 51db98f33c15
Create Date: 2026-09-02 09:49:48.371920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d67168d9cbd'
down_revision: Union[str, Sequence[str], None] = '51db98f33c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_skill_matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_match_id', sa.String(), nullable=False),
    sa.Column('skill', sa.String(), nullable=False),
    sa.Column('canonical_skill', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_match_id'], ['job_matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_match_id', 'skill', name='uq_job_skill_matches_match_skill')
    )
    op.create_index(op.f('ix_job_skill_matches_canonical_skill'), 'job_skill_matches', ['canonical_skill'], unique=False)
    op.create_index(op.f('ix_job_skill_matches_job_match_id'), 'job_skill_matches', ['job_match_id'], unique=False)
    op.create_index(op.f('ix_job_skill_matches_status'), 'job_skill_matches', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_skill_matches_status'), table_name='job_skill_matches')
    op.drop_index(op.f('ix_job_skill_matches_job_match_id'), table_name='job_skill_matches')
    op.drop_index(op.f('ix_job_skill_matches_canonical_skill'), table_name='job_skill_matches')
    op.drop_table('job_skill_matches')
    # ### end Alembic commands ###
