"""add profile display fields

Revision ID: 60e0f28716e5
Revises: 7215f2c15d52
Create Date: 2026-09-02 14:36:48.197374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e0f28716e5'
down_revision: Union[str, Sequence[str], None] = '7215f2c15d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Colonnes ajoutées à des tables déjà peuplées : un server_default
    # est nécessaire pour que SQLite sache quoi mettre dans les lignes
    # existantes (candidate-demo, l'expérience Ticketis...).
    # Il est retiré juste après pour rester fidèle au modèle Python
    # (default="" appliqué côté application, pas en base).
    op.add_column(
        'candidates',
        sa.Column(
            'headline', sa.String(), nullable=False, server_default=''
        ),
    )
    op.add_column(
        'candidates',
        sa.Column(
            'availability', sa.String(), nullable=False, server_default=''
        ),
    )
    op.add_column(
        'candidates',
        sa.Column(
            'languages', sa.Text(), nullable=False, server_default=''
        ),
    )
    op.add_column(
        'candidates',
        sa.Column(
            'interests', sa.Text(), nullable=False, server_default=''
        ),
    )
    op.add_column(
        'experiences',
        sa.Column(
            'location', sa.String(), nullable=False, server_default=''
        ),
    )

    with op.batch_alter_table('candidates') as batch_op:
        batch_op.alter_column('headline', server_default=None)
        batch_op.alter_column('availability', server_default=None)
        batch_op.alter_column('languages', server_default=None)
        batch_op.alter_column('interests', server_default=None)

    with op.batch_alter_table('experiences') as batch_op:
        batch_op.alter_column('location', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiences', 'location')
    op.drop_column('candidates', 'interests')
    op.drop_column('candidates', 'languages')
    op.drop_column('candidates', 'availability')
    op.drop_column('candidates', 'headline')
    # ### end Alembic commands ###
