"""add job offer remote details

Revision ID: 811b8a792a04
Revises: e7c62a411079
Create Date: 2026-09-02 20:18:54.378316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '811b8a792a04'
down_revision: Union[str, Sequence[str], None] = 'e7c62a411079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Colonne ajoutée à une table déjà peuplée (annonces existantes) :
    # un server_default est nécessaire pour SQLite, retiré juste après
    # pour rester fidèle au modèle Python (default="" côté
    # application), comme pour les migrations précédentes du même type.
    op.add_column(
        'job_offers',
        sa.Column(
            'remote_details', sa.String(), nullable=False, server_default=''
        ),
    )

    with op.batch_alter_table('job_offers') as batch_op:
        batch_op.alter_column('remote_details', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_offers', 'remote_details')
    # ### end Alembic commands ###
