"""create generated cvs

Revision ID: 9dede39dcac8
Revises: 1caa8ba11920
Create Date: 2026-09-03 15:43:48.125728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dede39dcac8'
down_revision: Union[str, Sequence[str], None] = '1caa8ba11920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_cvs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('job_offer_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=False),
    sa.Column('selected_experience_ids', sa.JSON(), nullable=False),
    sa.Column('selected_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('selected_skills', sa.JSON(), nullable=False),
    sa.Column('excluded_skills', sa.JSON(), nullable=False),
    sa.Column('match_score_at_generation', sa.Float(), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.Column('validation_issues', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_cvs_candidate_id'), 'generated_cvs', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_generated_cvs_job_offer_id'), 'generated_cvs', ['job_offer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_cvs_job_offer_id'), table_name='generated_cvs')
    op.drop_index(op.f('ix_generated_cvs_candidate_id'), table_name='generated_cvs')
    op.drop_table('generated_cvs')
    # ### end Alembic commands ###
