"""ajout selected_achievement_ids a generated_cvs

Revision ID: e7a58c5ffb33
Revises: 9dede39dcac8
Create Date: 2026-09-03 23:49:20.879409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7a58c5ffb33'
down_revision: Union[str, Sequence[str], None] = '9dede39dcac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    La table contient déjà des traces : une colonne NOT NULL ne peut
    pas y être ajoutée sans valeur par défaut. On la pose le temps de
    remplir les lignes existantes, puis on la retire — le défaut
    appartient au modèle, pas au schéma.
    """

    op.add_column(
        'generated_cvs',
        sa.Column(
            'selected_achievement_ids',
            sa.JSON(),
            nullable=False,
            server_default='[]',
        ),
    )

    with op.batch_alter_table('generated_cvs') as batch_op:
        batch_op.alter_column(
            'selected_achievement_ids',
            server_default=None,
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_cvs', 'selected_achievement_ids')
    # ### end Alembic commands ###
