"""add candidate motivations

Revision ID: e7c62a411079
Revises: 60e0f28716e5
Create Date: 2026-09-02 19:50:27.693704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c62a411079'
down_revision: Union[str, Sequence[str], None] = '60e0f28716e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Colonne ajoutée à une table déjà peuplée : un server_default est
    # nécessaire pour que SQLite sache quoi mettre dans les lignes
    # existantes (candidate-wissem). Il est retiré juste après pour
    # rester fidèle au modèle Python (default="" côté application).
    op.add_column(
        'candidates',
        sa.Column(
            'motivations', sa.Text(), nullable=False, server_default=''
        ),
    )

    with op.batch_alter_table('candidates') as batch_op:
        batch_op.alter_column('motivations', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'motivations')
    # ### end Alembic commands ###
