"""table skill_candidates

Revision ID: eddfd0b1c0f6
Revises: e7a58c5ffb33
Create Date: 2026-09-04 08:58:34.039312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eddfd0b1c0f6'
down_revision: Union[str, Sequence[str], None] = 'e7a58c5ffb33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('canonical_key', sa.String(), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('was_counted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolved_skill_id', sa.String(), nullable=True),
    sa.Column('job_offer_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_candidates_canonical_key'), 'skill_candidates', ['canonical_key'], unique=True)
    op.create_index(op.f('ix_skill_candidates_status'), 'skill_candidates', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_candidates_status'), table_name='skill_candidates')
    op.drop_index(op.f('ix_skill_candidates_canonical_key'), table_name='skill_candidates')
    op.drop_table('skill_candidates')
    # ### end Alembic commands ###
